services:
  postgres:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=root
      - POSTGRES_DB=portaldb
# postgresql://admin:abc123@localhost:5432/hacker_portal_dev
