# version: '3.9'
# docker-compose up db    # start db
# docker-compose exec db bash    # start shell in this container
services:
    db:
        image: postgres:14-alpine
        container_name: postgres_container
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: '12345'
            POSTGRES_DB: portaldb
        ports:
            - '5434:5432'
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
# postgres://root:12345@localhost:5432/portaldb
