version: '3.9'
# docker-compose up db
# docker-compose exec db bash
services:
  db:
    image: postgres:14-alpine
    container_name: postgres_container
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: portaldb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
