export interface Project {
    [key: number]: string;
}

export const projectsData: Project[] = [
    {
        0: '6',
        1: 'Battle Buddy',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
    {
        0: '1002',
        1: 'Battle Buddy - A Teamfight Tactics App A Teamfight Tactics App A Teamfight Tactics App',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
    {
        0: '1003',
        1: 'Battle Buddy',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
    {
        0: '1005',
        1: 'Battle Buddy - A Teamfight Tactics App 4',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
    {
        0: '1008',
        1: 'Battle Buddy - A Teamfight Tactics App 5',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
    {
        0: '1009',
        1: 'Battle Buddy - A Teamfight Tactics App 6',
        2: 'A desktop app that displays the top tier compositions in the meta along with the best units to run and their best-in-slot items. Updated each patch with data gathered from challenger tier lists!',
        3: 'https://www.youtube.com/watch?v=1O-i-wH-rhc&pp=ygUNYnJpYW4gcmFoYWRhaQ%3D%3D',
        4: 'Reimagine the Future',
        5: 'Yes, we used AI to generate some or all visuals',
        6: 'Yes, all external resources were properly cited',
        7: 'Yes, all AI tools are cited and their usage is clearly explained',
    },
];
