name: DevPipeline

on:
  pull_request: {}

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies"
          pnpm install
      - name: Run Linting
        run: |
          echo "Running Linting tests"
          pnpm run lint
      - name: Run Prettier
        run: |
          echo "Running Prettier"
          pnpm run prettier:check
      - name: Build
        run: |
          pnpm run build
